// Enhance an already readable static edition with the Museum's trusted viewer.
const record=JSON.parse(document.getElementById('orb-data').textContent);
const metadata=JSON.parse(document.getElementById('city-metadata').textContent);
const layout=document.querySelector('.portable-layout'),points=document.getElementById('orb-points');
if(layout&&points){
 const article=layout.querySelector('article'),header=document.querySelector('body>header'),fallback=document.getElementById('static-reader');
 const make=(tag,text)=>{const el=document.createElement(tag);if(text)el.textContent=text;return el;};
 const intro=fallback.querySelector('.city-introduction');layout.before(intro);
 const full=make('details');full.className='city-full-readings';full.append(make('summary','Read all eight points & sources'),fallback.querySelector('#complete-readings'));
 for(const el of full.querySelectorAll('.city-full-point'))el.id='full-'+el.id;
 const collection=fallback.querySelector('.city-collection');document.body.append(full,collection);fallback.remove();
 const returnLink=make('a','Today’s ORBs');returnLink.href='https://orbiversity.com/orb-archive/#todays-orbs';header?.append(returnLink);
 const footer=document.querySelector('footer');if(footer)footer.textContent='A read-only edition · Sources and discovered media open their original providers. No AI connection or account needed.';
 // Keep a Museum edition read-only. These known blocks are generated by the
 // shared portable runtime; authored source links are never removed.
 for(const link of document.querySelectorAll('.portable-layout>article a[href^="https://www.orbforma.com/nano.html?q="]')){
   if(link.parentElement.matches('section')&&link.parentElement.children.length===2)link.parentElement.remove();else link.remove();
 }
 const galleryLinks=make('section');galleryLinks.className='city-point-sources';article.append(galleryLinks);
 let panel=null,last=-1;
 const index=()=>Number(points.querySelector('[aria-current="true"][data-point]')?.dataset.point??0);
 function update(){
  const point=index();if(point===last)return;last=point;
  const reading=record.content.readings[point];if(!reading)return;
  history.replaceState(null,'','#'+reading.id);
  const ids=metadata.sourcePointAssignments.find(p=>p.id===reading.id)?.sourceIds||[];
  const list=make('ul');for(const source of metadata.sourceRegister.filter(s=>ids.includes(s.id))){const li=make('li'),a=make('a',source.title);a.href=source.url;a.rel='noopener noreferrer';a.target='_blank';li.append(a,make('small',source.publisher+' · Accessed '+source.accessedAt));list.append(li);}
  galleryLinks.replaceChildren(make('h3','Sources for this reading'),list);
  const directions=article.querySelector('.directions');
  if(directions){directions.replaceChildren();const add=(i,label)=>{const b=make('button',label+record.content.readings[i].label);b.type='button';b.addEventListener('click',()=>points.querySelector('[data-point="'+i+'"]')?.click());directions.append(b);};if(reading.parent>=0)add(reading.parent,'Broader · ');record.content.readings.forEach((r,i)=>{if(r.parent===point&&i!==point)add(i,'Deeper · ');});}
  if(panel)void panel.update({record,listing:{id:metadata.id,title:record.content.title,url:location.href},point}).catch(()=>{});
 }
 function openHash(){const hash=decodeURIComponent(location.hash.slice(1)),i=record.content.readings.findIndex(p=>p.id===hash);if(i>=0){full.open=false;points.querySelector('[data-point="'+i+'"]')?.click();}}
 const initialHash=location.hash;openHash();if(!initialHash)update();
 const observer=new MutationObserver(update);observer.observe(points,{subtree:true,childList:true,attributes:true,attributeFilter:['aria-current']});
 window.addEventListener('hashchange',openHash);
 full.addEventListener('click',event=>{const a=event.target.closest('a[href^="#"]');if(a)full.open=true;});
 try{const {mountMuseumMediaPanel}=await import('./museum-media-panel.mjs');panel=mountMuseumMediaPanel({onChoosePoint(i){points.querySelector('[data-point="'+i+'"]')?.click();}});article.prepend(panel.element);document.body.classList.add('museum-media-ready');last=-1;update();}catch{update();}
 window.addEventListener('pagehide',()=>panel?.stop());
}
